### ISSUE TITLE
f-ligatures are uneven

### ISSUE THREAD

**Issue by ortoslon** [huertatipografica/Andada-Pro#20]
Problems with "f" in ligatures at some sizes:
* the crossbar is thinner than in the unligated "f"
* the joining stroke is slightly below or above the top serif in "i"/"l"
* the bottom serif is off the baseline

https://github.com/huertatipografica/Andada-Pro/blob/129785ebf91d19507bb77f321d20c0c3114cbea5/fonts/ttf/AndadaPro-Regular.ttf and https://github.com/huertatipografica/Andada-Pro/blob/129785ebf91d19507bb77f321d20c0c3114cbea5/fonts/ttf/AndadaPro-Medium.ttf in Chrome 90 on Win10:
![image](https://user-images.githubusercontent.com/79928123/119153252-49648400-ba7b-11eb-8c44-f56084896a28.png)

**Comment by ortoslon** [comment]
Reproducing after https://github.com/huertatipografica/Andada-Pro/commit/9caa99c2e30d909462111a0125a72ac0f5fd6ee8:
![image](https://user-images.githubusercontent.com/79928123/119363121-a52b4900-bcd7-11eb-8206-ce8a147e32a1.png)

**Comment by CaroGiovagnoli** [comment]
![Screenshot 2021-05-25 at 13 36 06 copy](https://user-images.githubusercontent.com/8618171/119491513-4a890000-bd5e-11eb-826c-4209c68956c1.jpg)
![Screenshot 2021-05-25 at 13 35 47 copy](https://user-images.githubusercontent.com/8618171/119491521-4ceb5a00-bd5e-11eb-8f45-8ed0679155dc.jpg)

**Comment by ortoslon** [comment]
@CaroGiovagnoli, those screenshots have fonts scaled 2x, so 18 px = 36 ppem in terms of physical pixels. My screenshots aren't scaled (px = ppem).

Reproducing in https://github.com/huertatipografica/Andada-Pro/blob/9e59cad496923851384fcd47c55d82dea9f186a3/fonts/ttf/AndadaPro-Regular.ttf and https://github.com/huertatipografica/Andada-Pro/blob/9e59cad496923851384fcd47c55d82dea9f186a3/fonts/ttf/AndadaPro-Medium.ttf. Added 36 px = 36 ppem for comparison; it doesn't show problems.
![image](https://user-images.githubusercontent.com/79928123/119505079-c9019400-bd96-11eb-8eb0-84784e1a2796.png)

**Comment by CaroGiovagnoli** [comment]
Which OS and version are you using? Windows?

**Comment by ortoslon** [comment]
Chrome on Windows 10, as I wrote in the first comment.

**Comment by ortoslon** [comment]
Yes, looks fixed after https://github.com/huertatipografica/Andada-Pro/commit/bc76db05bb47a098058e442ac9c43c24b1ee7974. The "fl" join seems lighter at some sizes, but this might be inevitable with autohinting.
![image](https://user-images.githubusercontent.com/79928123/119663508-9ae68780-be5c-11eb-8317-c13403d0a556.png)

**Comment by CaroGiovagnoli** [comment]
The problems are:
- fl in 18x 17x 14x 13x split up
- fi 27x to 23x have an extra black pixel on the i

(The font is too curvy to be really autohinting friendly)

![regular-medium](https://user-images.githubusercontent.com/8618171/119666155-63181980-be35-11eb-8eda-13b4e4286261.jpg)

**Comment by ortoslon** [comment]
@CaroGiovagnoli, I've just noticed that the ligated "ff" still has similar problems.
https://github.com/huertatipografica/Andada-Pro/blob/bc76db05bb47a098058e442ac9c43c24b1ee7974/fonts/ttf/AndadaPro-Medium.ttf:
![image](https://user-images.githubusercontent.com/79928123/120326876-6159c480-c313-11eb-85be-e77302a1080a.png)

**Comment by CaroGiovagnoli** [comment]
![medium](https://user-images.githubusercontent.com/8618171/120333521-137f9500-c2f0-11eb-872c-a4099c43ff38.jpg)
![regular](https://user-images.githubusercontent.com/8618171/120333541-17131c00-c2f0-11eb-8719-7f6eaf2dc5f6.jpg)

It was an issue with the superposition of the horizontal stem.

**Comment by ortoslon** [comment]
Bottom serifs are still off the baseline:
![image](https://user-images.githubusercontent.com/79928123/120334994-51de7980-c31b-11eb-97a9-159e1977dbd5.png)

**Comment by CaroGiovagnoli** [comment]
![U
![regular2](https://user-images.githubusercontent.com/8618171/120396334-ae02c700-c336-11eb-8f4e-7914c626da3b.jpg)
ploading medium2.jpg…]()

**Comment by ortoslon** [comment]
Reproducing in https://github.com/huertatipografica/Andada-Pro/blob/4c06785c2b890c7dff6a909e05c4a0a3283a25b0/fonts/ttf/AndadaPro-Medium.ttf:

![image](https://user-images.githubusercontent.com/79928123/120486025-db0ab480-c3de-11eb-9251-097548404d03.png)

**Comment by CaroGiovagnoli** [comment]
The serif and stem have little curvy details, therefore there are some sizes that aren't autohinting friendly.
