### ISSUE TITLE
Font build instructions error

### ISSUE THREAD

**Issue by fiernot** [huertatipografica/Andada-Pro#21]
Hello @CaroGiovagnoli and @RosaWagner 

There is an error in the build instructions [here](https://github.com/huertatipografica/Andada-Pro#building-the-font).

It is stated there to run `pip3 -m env env`. `pip3` is only used to install/update/remove packages. It is the `python` binary that is used to create the virtual environment, like this:

`python3 -m env env` 

Of course, using `python3`, `pip3`, `python` or `pip` depends on your build environment. My comments are based on MacOS, where Python 3 is **not** the default installed version.

**Comment by RosaWagner** [comment]
apologies, it is indeed the command:

`python3 -m venv env`

I don't know why I wrote pip3 honnestly

**Comment by RosaWagner** [comment]
It is fixed :)

**Comment by fiernot** [comment]
Thanks!
