### ISSUE TITLE
Italic f swash

### ISSUE THREAD

**Issue by davelab6** [huertatipografica/Andada-Pro#22]
While https://github.com/huertatipografica/Andada-Pro/issues/20 is about roman ligatures, I have a concern about the italic 'f', when looking at https://fonts.google.com/specimen/Andada+Pro

<img width="1087" alt="Screen Shot 2021-08-05 at 11 13 43 AM" src="https://user-images.githubusercontent.com/261579/128374898-ba7d5dc6-d960-4882-b318-aa81d3ddfe44.png">

It seems unexpected to see that 'f' in the 'ft' pair is swashed

**Comment by CaroGiovagnoli** [comment]
Thanks!
