### ISSUE TITLE
Hyphen glyph: double dash intentional?

### ISSUE THREAD

**Issue by rajeeshknambiar** [huertatipografica/Andada-Pro#27]
Thanks for the beautiful Andada font, being a libre font!

I have noticed that the Hyphen (`U+2010`) glyph has 2 dashes (or a dash with break in the middle), which looks different from Hyphen-Minus (`U+002D`) and Soft-Hypehn (`U+00AD`), see attached screenshot.

![image](https://user-images.githubusercontent.com/424259/142997914-5c977ec0-86db-442e-a55a-76ea3e0d3bce.png)

Is this design intentional? Otherwise it doesn't look good when words are hyphenated (see screenshot).

![image](https://user-images.githubusercontent.com/424259/142998614-be1811dc-8a80-428b-9cc0-e0c935f4fb96.png)

**Comment by CaroGiovagnoli** [comment]
Hi, there are three hyphens, the `soft hyphen` is the same as a `hyphen` and there is also `hyphentwo` which is the hyphen that you show in the second image.
Which keyboard language distribution are you using?

[
![hyphen](https://user-images.githubusercontent.com/8618171/143199722-ce22e4b7-5cfb-4bda-9c96-db24a5b3c4b2.jpg)
](url)

**Comment by rajeeshknambiar** [comment]
Thank you for checking.

These hyphen characters were not manually input via keyboard; but a web page with automatic hyphenationn, displayed by Google Chromium browser. Now that I checked again, to my surprise, only Chrome/Chromium shows the `hyphentwo` — Firefox displays proper (single) hyphen!

You may check this page: https://rajeesh.cc/home.html on Chrome, enable `Developer Tools`, select first paragraph using the pointer tool; and change `font-family` to `"Andada Pro"` in the `.post-content` block (assuming you have the font locally installed).

**Comment by CaroGiovagnoli** [comment]
Thanks for the issue, if this is a problem related to how Chromium, I will close the issue. If you find something else feel free to reopen it.

**Comment by garrettm30** [comment]
Hi. I would like to report that I also am encountering the same issue (double hyphen in automatic hyphenation) in the layout application Affinity Publisher on Mac. This is the only font I can find that does this. If I change the text to, for example, Alegreya or Bitter, the automatic hyphenation uses a single hyphen as expected.
