### ISSUE TITLE
Request for Woun-Meu language

### ISSUE THREAD

**Issue by marisarabia** [huertatipografica/Andada-Pro#30]
Hi, 

In Proyecto Comarca, we are working with the Wounaan indigenous community from Panama. When selecting fonts to properly represent the signs of Woun-Meu language, Andada was very good. It would be great if some extra signs can be added. They are listed bellow. 

Many thanks in advance!

Ig: [@proyectoComarca](
https://www.instagram.com/proyectocomarca/)
GitHub: [@proyectoComarca](https://github.com/proyectoComarca)

Ꞌ: U+A78B : LATIN CAPITAL LETTER SALTILLO
ꞌ: U+A78C : LATIN SMALL LETTER SALTILLO
ʌ: U+028C : LATIN SMALL LETTER TURNED V {caret, wedge}
Ʌ: U+0245 : LATIN CAPITAL LETTER TURNED V
ʌ̃: U+028C : LATIN SMALL LETTER TURNED V {caret, wedge}
U+0303 : COMBINING TILDE
Ʌ̃: U+0245 : LATIN CAPITAL LETTER TURNED V
U+0303 : COMBINING TILDE
ʌ̈: U+028C : LATIN SMALL LETTER TURNED V {caret, wedge}
U+0308 : COMBINING DIAERESIS {double dot above, umlaut; Greek dialytika; double derivative}
Ʌ̈: U+0245 : LATIN CAPITAL LETTER TURNED V
U+0308 : COMBINING DIAERESIS {double dot above, umlaut; Greek dialytika; double derivative}
ʌ́: U+028C : LATIN SMALL LETTER TURNED V {caret, wedge}
U+0301 : COMBINING ACUTE ACCENT {stress mark; Greek oxia, tonos}
Ʌ́: U+0245 : LATIN CAPITAL LETTER TURNED V
U+0301 : COMBINING ACUTE ACCENT {stress mark; Greek oxia, tonos}

**Comment by CaroGiovagnoli** [comment]
The requested signs were created. Closing this issue.
